services:
  - type: web
    name: attendance-bot
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: TWILIO_ACCOUNT_SID
        value: your_twilio_sid
      - key: TWILIO_AUTH_TOKEN
        value: your_twilio_auth_token
      - key: TWILIO_WHATSAPP_FROM
        value: whatsapp:+14155238886
